# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# 				1_HALF-leaf Isocenter
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# - - - - - - - - - -1_Half_leaf_isocenter1 SUPERIOR PART box- - - - - - - - - - - - - - - -
# 
/gate/MLCbox/daughters/name HLI_SUP1_180S
/gate/MLCbox/daughters/insert box
/gate/HLI_SUP1_180S/setMaterial Air
/gate/HLI_SUP1_180S/geometry/setXLength 180.0 mm
/gate/HLI_SUP1_180S/geometry/setYLength 32.5 mm
/gate/HLI_SUP1_180S/geometry/setZLength 2.1 mm
/gate/HLI_SUP1_180S/vis/setColor white
/gate/HLI_SUP1_180S/placement/setTranslation 0.0 0.0 0.0 mm 
/gate/HLI_SUP1_180S/vis/setVisible 0

/gate/HLI_SUP1_180S/daughters/name HLI_SUP1_180
/gate/HLI_SUP1_180S/daughters/insert box
/gate/HLI_SUP1_180/setMaterial Air
/gate/HLI_SUP1_180/geometry/setXLength 180.0 mm
/gate/HLI_SUP1_180/geometry/setYLength 32.5 mm
/gate/HLI_SUP1_180/geometry/setZLength 2.1 mm
/gate/HLI_SUP1_180/vis/setColor white
/gate/HLI_SUP1_180/placement/setTranslation 0.0 0.0 0.0 mm 
/gate/HLI_SUP1_180/placement/setRotationAxis 0 1 0 
/gate/HLI_SUP1_180/placement/setRotationAngle 180 deg
/gate/HLI_SUP1_180/vis/setVisible 0

# 
# 
# 
# - - - - - - - - - -1_Half_leaf_isocenter SUPERIOR_1 PART FORMED AS A WEDGE- - - - - - - - - - - - - - - - 


/gate/HLI_SUP1_180/daughters/name Half_leaf_isocenter_SUP1_180
/gate/HLI_SUP1_180/daughters/insert wedge
/gate/Half_leaf_isocenter_SUP1_180/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Half_leaf_isocenter_SUP1_180/geometry/setNarrowerXLength  20.0 mm
/gate/Half_leaf_isocenter_SUP1_180/geometry/setXLength  176.908603971 mm
/gate/Half_leaf_isocenter_SUP1_180/geometry/setYLength  31.3 mm
/gate/Half_leaf_isocenter_SUP1_180/geometry/setZLength  2.1 mm
/gate/Half_leaf_isocenter_SUP1_180/placement/setRotationAxis 0 0 1    
/gate/Half_leaf_isocenter_SUP1_180/placement/setRotationAngle 180 deg
/gate/Half_leaf_isocenter_SUP1_180/placement/setTranslation 40.772849007250002 -0.6 0.0 mm 
/gate/Half_leaf_isocenter_SUP1_180/vis/setColor grey
/gate/Half_leaf_isocenter_SUP1_180/vis/forceSolid 1
/gate/Half_leaf_isocenter_SUP1_180/vis/setVisible 1
# 
# - - - - - - - - - 1_Half-leaf target isocenter_1 PART FORMED AS A PART OF A CYLINDER- - - - - - - - - - - 


/gate/HLI_SUP1_180/daughters/name Half_leaf_isocenter_round_sup1_180
/gate/HLI_SUP1_180/daughters/insert cylinder
/gate/Half_leaf_isocenter_round_sup1_180/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Half_leaf_isocenter_round_sup1_180/geometry/setRmin 0 mm
/gate/Half_leaf_isocenter_round_sup1_180/geometry/setRmax 160 mm
/gate/Half_leaf_isocenter_round_sup1_180/geometry/setHeight 2.1 mm
/gate/Half_leaf_isocenter_round_sup1_180/geometry/setPhiStart -11.2812366582 deg
/gate/Half_leaf_isocenter_round_sup1_180/geometry/setDeltaPhi 11.2812366582 deg
/gate/Half_leaf_isocenter_round_sup1_180/placement/setTranslation 70.0 -16.25 0.0 mm 
/gate/Half_leaf_isocenter_round_sup1_180/placement/setRotationAxis 0 0 1
/gate/Half_leaf_isocenter_round_sup1_180/placement/setRotationAngle 180 deg
/gate/Half_leaf_isocenter_round_sup1_180/vis/setColor grey
/gate/Half_leaf_isocenter_round_sup1_180/vis/forceSolid 1
/gate/Half_leaf_isocenter_round_sup1_180/vis/setVisible 1
# 
# 
# - - - - - - - - - -1_Half_leaf_isocenter SUPERIOR_1 PART Tip box FORMED AS A WEDGE- - - - - - - - - - - - - - - - 
# 
/gate/HLI_SUP1_180/daughters/name HLI_Tip_box180 #HLI Tip box to perform double rotation
/gate/HLI_SUP1_180/daughters/insert box
/gate/HLI_Tip_box180/setMaterial Air
/gate/HLI_Tip_box180/geometry/setXLength 180.0 mm
/gate/HLI_Tip_box180/geometry/setYLength 1.2 mm
/gate/HLI_Tip_box180/geometry/setZLength 2.1 mm
/gate/HLI_Tip_box180/placement/setTranslation 0.0 15.65 0.0 mm 
/gate/HLI_Tip_box180/placement/setRotationAxis 1 0 0 
/gate/HLI_Tip_box180/placement/setRotationAngle 180 deg
/gate/HLI_Tip_box180/vis/setColor white 
/gate/HLI_Tip_box180/vis/setVisible 0



/gate/HLI_Tip_box180/daughters/name Half_leaf_isocenter_SUP1_Tip_180
/gate/HLI_Tip_box180/daughters/insert wedge
/gate/Half_leaf_isocenter_SUP1_Tip_180/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Half_leaf_isocenter_SUP1_Tip_180/geometry/setNarrowerXLength  176.664450339 mm
/gate/Half_leaf_isocenter_SUP1_Tip_180/geometry/setXLength  176.908603971 mm
/gate/Half_leaf_isocenter_SUP1_Tip_180/geometry/setYLength  1.2 mm
/gate/Half_leaf_isocenter_SUP1_Tip_180/geometry/setZLength  0.75 mm
/gate/Half_leaf_isocenter_SUP1_Tip_180/placement/setRotationAxis 0 0 1    
/gate/Half_leaf_isocenter_SUP1_Tip_180/placement/setRotationAngle 180 deg
/gate/Half_leaf_isocenter_SUP1_Tip_180/placement/setTranslation 1.606736422499992 0.0 -0.675 mm 
/gate/Half_leaf_isocenter_SUP1_Tip_180/vis/setColor grey
/gate/Half_leaf_isocenter_SUP1_Tip_180/vis/forceSolid 1
/gate/Half_leaf_isocenter_SUP1_Tip_180/vis/setVisible 1
# 
# - - - - - - - - - -1_Half_leaf_isocenter1 SUPEROIOR PART Repeater- - - - - - - - - - - - - - - - 

/gate/HLI_SUP1_180S/moves/insert genericRepeaterMove
/gate/HLI_SUP1_180S/genericRepeaterMove/setPlacementsFilename DIR/precise_HLI_SUP180.placements
/gate/HLI_SUP1_180S/genericRepeaterMove/useRelativeTranslation 1


#-------------ALLL HL INF---------------------
#-------------ALLL HL INF---------------------
#-------------ALLL HL INF---------------------

/gate/MLCbox/daughters/name HLI_INFALL_180S
/gate/MLCbox/daughters/insert box
/gate/HLI_INFALL_180S/setMaterial Air
/gate/HLI_INFALL_180S/geometry/setXLength 180.0 mm
/gate/HLI_INFALL_180S/geometry/setYLength 34.5 mm
/gate/HLI_INFALL_180S/geometry/setZLength 2.9 mm
/gate/HLI_INFALL_180S/vis/setColor white
/gate/HLI_INFALL_180S/placement/setTranslation 0.0 0.0 0.0 mm 
/gate/HLI_INFALL_180S/vis/setVisible 0


/gate/HLI_INFALL_180S/daughters/name HLI_INFALL_180
/gate/HLI_INFALL_180S/daughters/insert box
/gate/HLI_INFALL_180/setMaterial Air
/gate/HLI_INFALL_180/geometry/setXLength 180.0 mm
/gate/HLI_INFALL_180/geometry/setYLength 34.5 mm
/gate/HLI_INFALL_180/geometry/setZLength 2.9 mm
/gate/HLI_INFALL_180/vis/setColor white
/gate/HLI_INFALL_180/placement/setTranslation 0.0 0.0 0.0 mm 
/gate/HLI_INFALL_180/placement/setRotationAxis 0 1 0 
/gate/HLI_INFALL_180/placement/setRotationAngle 180 deg
/gate/HLI_INFALL_180/vis/setVisible 0






# - - - - - - - - - -1_Half_leaf_isocenter2 SUPERIOR PART box- - - - - - - - - - - - - - - -

/gate/HLI_INFALL_180/daughters/name HLI_SUP2180
/gate/HLI_INFALL_180/daughters/insert box
/gate/HLI_SUP2180/setMaterial AcceleratorCollimatorLeafMaterial
/gate/HLI_SUP2180/placement/setTranslation 0.0 17.05 0.2 mm
/gate/HLI_SUP2180/geometry/setXLength 180.0 mm
/gate/HLI_SUP2180/geometry/setYLength 0.4 mm
/gate/HLI_SUP2180/geometry/setZLength 2.5 mm
/gate/HLI_SUP2180/vis/setColor grey
/gate/HLI_SUP2180/vis/forceSolid 1
/gate/HLI_SUP2180/vis/setVisible 1


# - - - - - - - - - -1_Half-leaf isocenter INFERIOR PART box- - - - - - - - - - - - - - - -

/gate/HLI_INFALL_180/daughters/name HLI_INF180
/gate/HLI_INFALL_180/daughters/insert box
/gate/HLI_INF180/setMaterial Air
/gate/HLI_INF180/placement/setTranslation 0.0 -0.2 -0.0 mm
/gate/HLI_INF180/geometry/setXLength 180.0 mm
/gate/HLI_INF180/geometry/setYLength 34.1 mm
/gate/HLI_INF180/geometry/setZLength 2.9 mm
/gate/HLI_INF180/vis/setColor white
/gate/HLI_INF180/vis/setVisible 0




# - - - - - - - - - -1_Half-leaf isocenter INFERIOR PART FORMED AS A WEDGE- - - - - - - - - - - - - - - - - 


/gate/HLI_INF180/daughters/name Half_leaf_isocenter_INF180
/gate/HLI_INF180/daughters/insert wedge
/gate/Half_leaf_isocenter_INF180/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Half_leaf_isocenter_INF180/geometry/setNarrowerXLength  20.0 mm
/gate/Half_leaf_isocenter_INF180/geometry/setXLength  177.0660689009565 mm
/gate/Half_leaf_isocenter_INF180/geometry/setYLength  30.5 mm
/gate/Half_leaf_isocenter_INF180/geometry/setZLength  2.9 mm
/gate/Half_leaf_isocenter_INF180/placement/setRotationAxis 0 1 0    
/gate/Half_leaf_isocenter_INF180/placement/setRotationAngle 180 deg
/gate/Half_leaf_isocenter_INF180/placement/setTranslation 40.733482774760887 1.8 0.0 mm 
/gate/Half_leaf_isocenter_INF180/vis/setColor grey
/gate/Half_leaf_isocenter_INF180/vis/forceSolid 1
/gate/Half_leaf_isocenter_INF180/vis/setVisible 1



/gate/Half_leaf_isocenter_INF180/daughters/name Half_leaf_isocenter_INF_screwh180
/gate/Half_leaf_isocenter_INF180/daughters/insert wedge
/gate/Half_leaf_isocenter_INF_screwh180/setMaterial Air
/gate/Half_leaf_isocenter_INF_screwh180/geometry/setNarrowerXLength  81.281515407157414 mm
/gate/Half_leaf_isocenter_INF_screwh180/geometry/setXLength  98.275549091495179 mm
/gate/Half_leaf_isocenter_INF_screwh180/geometry/setYLength  3.3 mm
/gate/Half_leaf_isocenter_INF_screwh180/geometry/setZLength  2.9 mm
/gate/Half_leaf_isocenter_INF_screwh180/placement/setTranslation -4.377251100575975 1.7 0.0 mm 
/gate/Half_leaf_isocenter_INF_screwh180/vis/setColor black
/gate/Half_leaf_isocenter_INF_screwh180/vis/forceSolid 1
/gate/Half_leaf_isocenter_INF_screwh180/vis/setVisible 1



# - - - - - - - - - 1_Half-leaf target isocenter PART FORMED AS A PART OF A CYLINDER- - - - - - - - - - - 


/gate/HLI_INF180/daughters/name Half_leaf_isocenter_round_inf180
/gate/HLI_INF180/daughters/insert cylinder
/gate/Half_leaf_isocenter_round_inf180/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Half_leaf_isocenter_round_inf180/geometry/setRmin 0 mm
/gate/Half_leaf_isocenter_round_inf180/geometry/setRmax 160 mm
/gate/Half_leaf_isocenter_round_inf180/geometry/setHeight 2.9 mm
/gate/Half_leaf_isocenter_round_inf180/geometry/setPhiStart 0  deg
/gate/Half_leaf_isocenter_round_inf180/geometry/setDeltaPhi 10.9892607227 deg
/gate/Half_leaf_isocenter_round_inf180/placement/setTranslation 70.0 17.05 0.0 mm 
/gate/Half_leaf_isocenter_round_inf180/placement/setRotationAxis 0 0 1
/gate/Half_leaf_isocenter_round_inf180/placement/setRotationAngle 180 deg
/gate/Half_leaf_isocenter_round_inf180/vis/setColor grey
/gate/Half_leaf_isocenter_round_inf180/vis/forceSolid 1
/gate/Half_leaf_isocenter_round_inf180/vis/setVisible 1



/gate/Half_leaf_isocenter_round_inf180/daughters/name Half_leaf_isocenter_round_inf_screwhC180
/gate/Half_leaf_isocenter_round_inf180/daughters/insert wedge
/gate/Half_leaf_isocenter_round_inf_screwhC180/setMaterial Air
/gate/Half_leaf_isocenter_round_inf_screwhC180/geometry/setNarrowerXLength  64.724450908504821 mm
/gate/Half_leaf_isocenter_round_inf_screwhC180/geometry/setXLength  81.718484592842586 mm
/gate/Half_leaf_isocenter_round_inf_screwhC180/geometry/setYLength  3.3 mm
/gate/Half_leaf_isocenter_round_inf_screwhC180/geometry/setZLength  2.9 mm
/gate/Half_leaf_isocenter_round_inf_screwhC180/placement/setRotationAxis 0 1 0    
/gate/Half_leaf_isocenter_round_inf_screwhC180/placement/setRotationAngle 180 deg
/gate/Half_leaf_isocenter_round_inf_screwhC180/placement/setTranslation 106.3892661246632 13.55 0.0 mm 
/gate/Half_leaf_isocenter_round_inf_screwhC180/vis/setColor black
/gate/Half_leaf_isocenter_round_inf_screwhC180/vis/forceSolid 1
/gate/Half_leaf_isocenter_round_inf_screwhC180/vis/setVisible 1
# 




# - - - - - - - - - 1_Half-leaf target isocenter inferior part wedge tip- - - - - - - - - - - 

/gate/HLI_INF180/daughters/name Half_leaf_isocenter_Inf1_Tip180
/gate/HLI_INF180/daughters/insert wedge
/gate/Half_leaf_isocenter_Inf1_Tip180/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Half_leaf_isocenter_Inf1_Tip180/geometry/setNarrowerXLength  176.5387811374549 mm
/gate/Half_leaf_isocenter_Inf1_Tip180/geometry/setXLength  177.0660689009565 mm
/gate/Half_leaf_isocenter_Inf1_Tip180/geometry/setYLength  2.6 mm
/gate/Half_leaf_isocenter_Inf1_Tip180/geometry/setZLength  1.49 mm
/gate/Half_leaf_isocenter_Inf1_Tip180/placement/setRotationAxis 0 0 1    
/gate/Half_leaf_isocenter_Inf1_Tip180/placement/setRotationAngle 180 deg
/gate/Half_leaf_isocenter_Inf1_Tip180/placement/setTranslation 1.598787490397157 -14.75 -0.705 mm 
/gate/Half_leaf_isocenter_Inf1_Tip180/vis/setColor grey
/gate/Half_leaf_isocenter_Inf1_Tip180/vis/forceSolid 1
/gate/Half_leaf_isocenter_Inf1_Tip180/vis/setVisible 1

# - - - - - - - - - 1_Half-leaf target isocenter inferior part wedge hole- - - - - - - - - - - 

/gate/HLI_INF180/daughters/name Half_leaf_isocenter_Inf1_hole180
/gate/HLI_INF180/daughters/insert wedge
/gate/Half_leaf_isocenter_Inf1_hole180/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Half_leaf_isocenter_Inf1_hole180/geometry/setNarrowerXLength  176.3239904813078 mm
/gate/Half_leaf_isocenter_Inf1_hole180/geometry/setXLength  176.5387811374549 mm
/gate/Half_leaf_isocenter_Inf1_hole180/geometry/setYLength  1.0 mm
/gate/Half_leaf_isocenter_Inf1_hole180/geometry/setZLength  2.9 mm
/gate/Half_leaf_isocenter_Inf1_hole180/placement/setRotationAxis 0 0 1    
/gate/Half_leaf_isocenter_Inf1_hole180/placement/setRotationAngle 180 deg
/gate/Half_leaf_isocenter_Inf1_hole180/placement/setTranslation 1.765387811374549 -16.55 0 mm 
/gate/Half_leaf_isocenter_Inf1_hole180/vis/setColor grey
/gate/Half_leaf_isocenter_Inf1_hole180/vis/forceSolid 1
/gate/Half_leaf_isocenter_Inf1_hole180/vis/setVisible 1
# - - - - - - - - - -ALLL HL INF Repeater- - - - - - - - - - - - - - - - 

/gate/HLI_INFALL_180S/moves/insert genericRepeaterMove
/gate/HLI_INFALL_180S/genericRepeaterMove/setPlacementsFilename DIR/precise_HLI_INF180.placements
/gate/HLI_INFALL_180S/genericRepeaterMove/useRelativeTranslation 1


