# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# 			 			HALF-leaf-RIGHT
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -





# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# 				1_HALF-leaf target
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# - - - - - - - - - -1_Half_leaf_target SUPERIOR PART box- - - - - - - - - - - - - - - - 



/gate/MLCbox/daughters/name HLT_SUP
/gate/MLCbox/daughters/insert box
/gate/HLT_SUP/setMaterial Air
/gate/HLT_SUP/geometry/setXLength 180.0 mm
/gate/HLT_SUP/geometry/setYLength 34.8 mm
/gate/HLT_SUP/geometry/setZLength 2.89 mm
/gate/HLT_SUP/vis/setColor white
/gate/HLT_SUP/placement/setTranslation 180.0 0.05 0.0 mm 
/gate/HLT_SUP/vis/setVisible 0




# - - - - - - - - - -1_Half_leaf_target SUPERIOR PART FORMED AS A WEDGE- - - - - - - - - - - - - - - - 

/gate/HLT_SUP/daughters/name Half_leaf_target_SUP
/gate/HLT_SUP/daughters/insert wedge
/gate/Half_leaf_target_SUP/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Half_leaf_target_SUP/geometry/setNarrowerXLength  20.0 mm
#/gate/Half_leaf_target_SUP/geometry/setXLength  156.24 mm
/gate/Half_leaf_target_SUP/geometry/setXLength  176.9483673059392 mm
/gate/Half_leaf_target_SUP/geometry/setYLength  31.1 mm
/gate/Half_leaf_target_SUP/geometry/setZLength  2.89 mm
/gate/Half_leaf_target_SUP/placement/setRotationAxis 0 0 1    
/gate/Half_leaf_target_SUP/placement/setRotationAngle 180 deg

/gate/Half_leaf_target_SUP/placement/setTranslation 40.762908173515200 -1.75 0.0 mm 
/gate/Half_leaf_target_SUP/vis/setColor white
/gate/Half_leaf_target_SUP/vis/forceSolid 1
/gate/Half_leaf_target_SUP/vis/setVisible 1


/gate/Half_leaf_target_SUP/daughters/name Half_leaf_target_SUP_screwhW
/gate/Half_leaf_target_SUP/daughters/insert wedge
/gate/Half_leaf_target_SUP_screwhW/setMaterial Air
/gate/Half_leaf_target_SUP_screwhW/geometry/setNarrowerXLength  72.988998608157445 mm
/gate/Half_leaf_target_SUP_screwhW/geometry/setXLength  89.642683885006932 mm
/gate/Half_leaf_target_SUP_screwhW/geometry/setYLength  3.3 mm
/gate/Half_leaf_target_SUP_screwhW/geometry/setZLength  2.89 mm
#/gate/Half_leaf_target_SUP_screwhW/placement/setRotationAxis 0 0 1    
#/gate/Half_leaf_target_SUP_screwhW/placement/setRotationAngle 180 deg
/gate/Half_leaf_target_SUP_screwhW/placement/setTranslation -8.579171203193710 3.4 0.0 mm 
/gate/Half_leaf_target_SUP_screwhW/vis/setColor black
/gate/Half_leaf_target_SUP_screwhW/vis/forceSolid 1
/gate/Half_leaf_target_SUP_screwhW/vis/setVisible 1


# - - - - - - - - - 1_Half-leaf target SUPERIOR PART FORMED AS A PART OF A CYLINDER- - - - - - - - - - - 


/gate/HLT_SUP/daughters/name Half_leaf_target_round_sup
/gate/HLT_SUP/daughters/insert cylinder

/gate/Half_leaf_target_round_sup/setMaterial AcceleratorCollimatorLeafMaterial

/gate/Half_leaf_target_round_sup/geometry/setRmin 0 mm
/gate/Half_leaf_target_round_sup/geometry/setRmax 160 mm
/gate/Half_leaf_target_round_sup/geometry/setHeight 2.89 mm
/gate/Half_leaf_target_round_sup/geometry/setPhiStart -11.2082151522 deg
/gate/Half_leaf_target_round_sup/geometry/setDeltaPhi 11.2082151522 deg
/gate/Half_leaf_target_round_sup/placement/setTranslation 70 -17.3 0.0 mm 
/gate/Half_leaf_target_round_sup/placement/setRotationAxis 0 0 1
/gate/Half_leaf_target_round_sup/placement/setRotationAngle 180 deg

/gate/Half_leaf_target_round_sup/vis/setColor white
/gate/Half_leaf_target_round_sup/vis/forceSolid 1

/gate/Half_leaf_target_round_sup/vis/setVisible 1


/gate/Half_leaf_target_round_sup/daughters/name Half_leaf_target_round_sup_screwhC
/gate/Half_leaf_target_round_sup/daughters/insert wedge
/gate/Half_leaf_target_round_sup_screwhC/setMaterial Air
/gate/Half_leaf_target_round_sup_screwhC/geometry/setNarrowerXLength  73.357316114993068 mm
/gate/Half_leaf_target_round_sup_screwhC/geometry/setXLength  90.011001391842555 mm
/gate/Half_leaf_target_round_sup_screwhC/geometry/setYLength  3.3 mm
/gate/Half_leaf_target_round_sup_screwhC/geometry/setZLength  2.89 mm
/gate/Half_leaf_target_round_sup_screwhC/placement/setRotationAxis 0 0 1    
/gate/Half_leaf_target_round_sup_screwhC/placement/setRotationAngle 180 deg
/gate/Half_leaf_target_round_sup_screwhC/placement/setTranslation  102.1579206232911 -12.15 0.0 mm 
/gate/Half_leaf_target_round_sup_screwhC/vis/setColor black
/gate/Half_leaf_target_round_sup_screwhC/vis/forceSolid 1
/gate/Half_leaf_target_round_sup_screwhC/vis/setVisible 1

# - - - - - - - - - 1_Half-leaf target inferior tip- - - - - - - - - - -

/gate/HLT_SUP/daughters/name ITip_HLT_SUP
/gate/HLT_SUP/daughters/insert box
/gate/ITip_HLT_SUP/setMaterial AcceleratorCollimatorLeafMaterial
/gate/ITip_HLT_SUP/geometry/setXLength 180.0 mm
/gate/ITip_HLT_SUP/geometry/setYLength 0.1 mm
/gate/ITip_HLT_SUP/geometry/setZLength 2.49 mm
/gate/ITip_HLT_SUP/placement/setTranslation 0.0 -17.35 -0.2 mm 
/gate/ITip_HLT_SUP/vis/setColor white
/gate/ITip_HLT_SUP/vis/forceSolid 1

/gate/ITip_HLT_SUP/vis/setVisible 1

# - - - - - - - - - 1_Half-leaf target superior Hole- - - - - - - - - - -
/gate/HLT_SUP/daughters/name Hole_HLT_SUP_box
/gate/HLT_SUP/daughters/insert box
/gate/Hole_HLT_SUP_box/setMaterial Air
/gate/Hole_HLT_SUP_box/geometry/setXLength 180.0 mm
/gate/Hole_HLT_SUP_box/geometry/setYLength 2.6 mm
/gate/Hole_HLT_SUP_box/geometry/setZLength 2.89 mm
/gate/Hole_HLT_SUP_box/placement/setRotationAxis 1 0 0    
/gate/Hole_HLT_SUP_box/placement/setRotationAngle 180 deg
/gate/Hole_HLT_SUP_box/placement/setTranslation 0.0 15.1 0.0 mm
/gate/Hole_HLT_SUP_box/vis/setVisible 0


/gate/Hole_HLT_SUP_box/daughters/name Hole_HLT_SUP
/gate/Hole_HLT_SUP_box/daughters/insert wedge
/gate/Hole_HLT_SUP/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Hole_HLT_SUP/geometry/setNarrowerXLength  176.4107093520134 mm
/gate/Hole_HLT_SUP/geometry/setXLength  176.9483673059392 mm
/gate/Hole_HLT_SUP/geometry/setYLength  2.6 mm
/gate/Hole_HLT_SUP/geometry/setZLength  1.52 mm
/gate/Hole_HLT_SUP/placement/setRotationAxis 0 0 1    
/gate/Hole_HLT_SUP/placement/setRotationAngle 180 deg
/gate/Hole_HLT_SUP/placement/setTranslation 1.660230835511854 0.0 -0.685 mm
/gate/Hole_HLT_SUP/vis/setColor white
/gate/Hole_HLT_SUP/vis/forceSolid 1
/gate/Hole_HLT_SUP/vis/setVisible 1
# 
# 
# 
# # - - - - - - - - - 1_Half-leaf target superior TIP- - - - - - - - - - -
# 
/gate/HLT_SUP/daughters/name STip_HLT_SUP_box
/gate/HLT_SUP/daughters/insert box
/gate/STip_HLT_SUP_box/setMaterial Air
/gate/STip_HLT_SUP_box/geometry/setXLength 180 mm
/gate/STip_HLT_SUP_box/geometry/setYLength 1.0 mm
/gate/STip_HLT_SUP_box/geometry/setZLength 2.89 mm
/gate/STip_HLT_SUP_box/placement/setTranslation 0.0 16.9 0.0 mm 
/gate/STip_HLT_SUP_box/placement/setRotationAxis 1 0 0    
/gate/STip_HLT_SUP_box/placement/setRotationAngle 180 deg
/gate/STip_HLT_SUP_box/vis/setColor red
/gate/STip_HLT_SUP_box/vis/forceSolid 0
/gate/STip_HLT_SUP_box/vis/setVisible 0

# 
/gate/STip_HLT_SUP_box/daughters/name STip_HLT_SUP
/gate/STip_HLT_SUP_box/daughters/insert wedge
/gate/STip_HLT_SUP/setMaterial AcceleratorCollimatorLeafMaterial
/gate/STip_HLT_SUP/geometry/setNarrowerXLength  176.1696513410976 mm
/gate/STip_HLT_SUP/geometry/setXLength  176.4107093520134 mm
/gate/STip_HLT_SUP/geometry/setYLength  1.0 mm
/gate/STip_HLT_SUP/geometry/setZLength  2.89 mm
/gate/STip_HLT_SUP/placement/setRotationAxis 0 0 1    
/gate/STip_HLT_SUP/placement/setRotationAngle 180 deg
/gate/STip_HLT_SUP/placement/setTranslation 1.854909826722249 0.0 0.0 mm
/gate/STip_HLT_SUP/vis/setColor white
/gate/STip_HLT_SUP/vis/forceSolid 1
/gate/STip_HLT_SUP/vis/setVisible 1

# - - - - - - - - - -1_Half_leaf_target SUPERIOR PART Repeater- - - - - - - - - - - - - - - - 

/gate/HLT_SUP/moves/insert genericRepeaterMove
/gate/HLT_SUP/genericRepeaterMove/setPlacementsFilename DIR/precise_HLT_SUP.placements
/gate/HLT_SUP/genericRepeaterMove/useRelativeTranslation 1

# 
# - - - - - - - - - -1_Half_leaf_target INFERIOR PART box- - - - - - - - - - - - - - - - 



/gate/MLCbox/daughters/name HLT_INF
/gate/MLCbox/daughters/insert box
/gate/HLT_INF/setMaterial Air
#/gate/HLT_INF/placement/setTranslation 0.0 -15.6 -15.586 mm
/gate/HLT_INF/geometry/setXLength 180.0 mm
/gate/HLT_INF/geometry/setYLength 32.2 mm
/gate/HLT_INF/geometry/setZLength 2.09 mm
/gate/HLT_INF/vis/setColor white
/gate/HLT_INF/placement/setTranslation 180.0 0.05 0.0 mm 
/gate/HLT_INF/vis/setVisible 0






# - - - - - - - - - -1_Half-leaf target INFERIOR PART FORMED AS A WEDGE- - - - - - - - - - - - - - - - - 
# 

/gate/HLT_INF/daughters/name Half_leaf_target_INF
/gate/HLT_INF/daughters/insert wedge
/gate/Half_leaf_target_INF/setMaterial AcceleratorCollimatorLeafMaterial


/gate/Half_leaf_target_INF/geometry/setNarrowerXLength  20.0 mm
#/gate/Half_leaf_target_INF/geometry/setXLength  156.24 mm
/gate/Half_leaf_target_INF/geometry/setXLength  176.9681496355232 mm
/gate/Half_leaf_target_INF/geometry/setYLength  31.0 mm
/gate/Half_leaf_target_INF/geometry/setZLength  2.09 mm
/gate/Half_leaf_target_INF/placement/setRotationAxis 0 1 0    
/gate/Half_leaf_target_INF/placement/setRotationAngle 180 deg

/gate/Half_leaf_target_INF/placement/setTranslation 40.757962591119203 0.6 0.0 mm 
/gate/Half_leaf_target_INF/vis/setColor white
/gate/Half_leaf_target_INF/vis/forceSolid 1
/gate/Half_leaf_target_INF/vis/setVisible 1






# 
# 
# - - - - - - - - - 1_Half-leaf target INFERIOR PART FORMED AS A PART OF A CYLINDER- - - - - - - - - - - 
# 

/gate/HLT_INF/daughters/name Hald_leaf_target_round_inf
/gate/HLT_INF/daughters/insert cylinder

/gate/Hald_leaf_target_round_inf/setMaterial AcceleratorCollimatorLeafMaterial


/gate/Hald_leaf_target_round_inf/geometry/setRmin 0 mm
/gate/Hald_leaf_target_round_inf/geometry/setRmax 160 mm
/gate/Hald_leaf_target_round_inf/geometry/setHeight 2.09 mm
/gate/Hald_leaf_target_round_inf/geometry/setPhiStart 0  deg
/gate/Hald_leaf_target_round_inf/geometry/setDeltaPhi 11.1717113211 deg
/gate/Hald_leaf_target_round_inf/placement/setTranslation 70.0 16.1 0.0 mm 
/gate/Hald_leaf_target_round_inf/placement/setRotationAxis 0 0 1
/gate/Hald_leaf_target_round_inf/placement/setRotationAngle 180 deg

/gate/Hald_leaf_target_round_inf/vis/setColor white
/gate/Hald_leaf_target_round_inf/vis/forceSolid 1
/gate/Hald_leaf_target_round_inf/vis/setVisible 1
# 
# 
# - - - - - - - - - 1_Half-leaf target Inferior TIP- - - - - - - - - - -
# 
/gate/HLT_INF/daughters/name Tip_HLT_Inf_box
/gate/HLT_INF/daughters/insert box
/gate/Tip_HLT_Inf_box/setMaterial Air
/gate/Tip_HLT_Inf_box/geometry/setXLength 180 mm
/gate/Tip_HLT_Inf_box/geometry/setYLength 1.2 mm
/gate/Tip_HLT_Inf_box/geometry/setZLength 1.05 mm
/gate/Tip_HLT_Inf_box/placement/setTranslation 0.0 -15.5 -0.52 mm 
/gate/Tip_HLT_Inf_box/vis/setColor red
/gate/Tip_HLT_Inf_box/vis/forceSolid 0
/gate/Tip_HLT_Inf_box/vis/setVisible 0


/gate/Tip_HLT_Inf_box/daughters/name Tip_HLT_Inf
/gate/Tip_HLT_Inf_box/daughters/insert wedge
/gate/Tip_HLT_Inf/setMaterial AcceleratorCollimatorLeafMaterial
/gate/Tip_HLT_Inf/geometry/setNarrowerXLength  176.7263857810803 mm
/gate/Tip_HLT_Inf/geometry/setXLength  176.9681496355232 mm
/gate/Tip_HLT_Inf/geometry/setYLength  1.2 mm
/gate/Tip_HLT_Inf/geometry/setZLength  1.05 mm
/gate/Tip_HLT_Inf/placement/setRotationAxis 0 0 1    
/gate/Tip_HLT_Inf/placement/setRotationAngle 180 deg
/gate/Tip_HLT_Inf/placement/setTranslation 1.576366145849121 0.0 0.0 mm
/gate/Tip_HLT_Inf/vis/setColor white
/gate/Tip_HLT_Inf/vis/forceSolid 1
/gate/Tip_HLT_Inf/vis/setVisible 1




# - - - - - - - - - -1_Half_leaf_target INFERIOR PART Repeater- - - - - - - - - - - - - - - - 
# 
/gate/HLT_INF/moves/insert genericRepeaterMove
/gate/HLT_INF/genericRepeaterMove/setPlacementsFilename DIR/precise_HLT_INF.placements
/gate/HLT_INF/genericRepeaterMove/useRelativeTranslation 1