# raw image can be opened with following options in Image J
# 32 bits reals Little endian
# W = sizex/voxelx  H = SizeY/voxelY Number of images SizeZ/voxelZ

/gate/actor/addActor DoseActor doseDistribution
/gate/actor/doseDistribution/save {out}/myDose.mhd
/gate/actor/doseDistribution/attachTo patient
/gate/actor/doseDistribution/stepHitType random

/gate/actor/doseDistribution/setSize 5 2 5 mm
/gate/actor/doseDistribution/setResolution 60 150 60 

/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableUncertaintyDose true

#/gate/actor/doseDistribution/enableEdep            true
#/gate/actor/doseDistribution/enableUncertaintyEdep true

/gate/actor/doseDistribution/enableDoseToWater true
/gate/actor/doseDistribution/enableUncertaintyDoseToWater true

/gate/actor/doseDistribution/saveEveryNSeconds     2000